FROM public.ecr.aws/docker/library/python:3.11
WORKDIR /code
COPY ./requirements/prod.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./src /code/src
ENV DEPLOY_ENV prod
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8282", "--log-level", "error"]